name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout dépôt
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      
      - name: Exécuter test à chaque push
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest src/tests/test_calculator.py

      - name: Install sshpass
        run: |
          # Ensure Homebrew runs natively on ARM for M2
          arch -arm64 brew update
          arch -arm64 brew install sshpass
          # Verify installation
          arch -arm64 sshpass -V

      - name: Deploy to VM
        env:
          VM_HOST: 10.194.32.173
          VM_PASSWORD: 88HC68NxZis2VVBV 
        run: |
          echo "$VM_PASSWORD" > password_file
          chmod 600 password_file
          
          arch -arm64 sshpass -f password_file ssh -o StrictHostKeyChecking=no log430@$VM_HOST << 'EOF'
            mkdir -p ~/my-app
            cd ~/my-app
            if [ -d ".git" ]; then
              git reset --hard
              git pull
            else
              git clone https://github.com/MariaRimaDev/log430-a25-labo0.git .
            fi
            # Construire l'image Docker
            docker build -t calculator-app .
            docker run --rm calculator-app echo "Container started successfully!"
          EOF
          
          rm password_file