name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout dépôt
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      
      - name: Exécuter test à chaque push
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest src/tests/test_calculator.py

      - name: Debug secrets
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}
        run: |
          echo "VM_HOST: $VM_HOST"
          echo "VM_SSH_KEY length: ${#VM_SSH_KEY}"


      - name: Deploy to VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}
        run: |
          echo "$VM_SSH_KEY" > ssh_key
          chmod 600 ssh_key
          
          ssh -i ssh_key -o StrictHostKeyChecking=no log430@$VM_HOST << 'EOF'
            mkdir -p ~/my-app
            cd ~/my-app
            if [ -d ".git" ]; then
              git reset --hard
              git pull
            else
              git clone https://github.com/MariaRimaDev/log430-a25-labo0.git .
            fi
            # Construire l'image Docker
            docker build -t calculator-app .
            docker run --rm calculator-app echo "Container started successfully!"
          EOF
          
          rm ssh_key